model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
  - model_name: deepseek-chat
    litellm_params:
      model: deepseek/deepseek-chat
  - model_name: deepseek-reasoner
    litellm_params:
      model: deepseek/deepseek-reasoner
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-04-17
